services:
  codeninja:
    container_name: codeninja
    build: .
    restart: unless-stopped
    ports:
      - "3005:3005"  # Expose HTTP port for MCP connections
    env_file:
      - .env  # Load environment variables from .env file
    environment:
      # Override specific values if needed
      - NODE_ENV=production
      - HTTP_PORT=3005
      - HTTP_HOST=0.0.0.0
    volumes:
      - ./logs:/app/logs
    networks:
      - codeninja-network

networks:
  codeninja-network:
    driver: bridge

# No n8n service needed - you already have it running!